# Generated by Django 3.1 on 2021-08-10 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppDips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watchlist_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high52', models.FloatField(default=0.0)),
                ('low52', models.FloatField(default=0.0)),
                ('lastPrice', models.FloatField(default=0.0)),
                ('price_list', models.CharField(blank=True, max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppDips.stocknames')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppWatchlists.watchlist')),
            ],
        ),
    ]
