# Generated by Django 3.1 on 2021-08-10 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockNames',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=264, unique=True)),
                ('companyName', models.CharField(max_length=264)),
            ],
            options={
                'verbose_name': 'StockNames',
                'verbose_name_plural': 'StockNames',
            },
        ),
    ]
